language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
env:
    - SYMFONY_VERSION="2.7" DB=mysql
    - SYMFONY_VERSION="2.8" DB=mysql
    - SYMFONY_VERSION="3.1" DB=mysql
before_script:
    - composer require --no-dev symfony/framework-bundle:${SYMFONY_VERSION}
script: phpunit --coverage-text
