language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
env:
    - SYMFONY_VERSION="2.7" DB=mysql
    - SYMFONY_VERSION="2.8" DB=mysql
    - SYMFONY_VERSION="3.1" DB=mysql
before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
script: phpunit --coverage-text
addons:
    code_climate:
        repo_token: f459b90bc135719bd144859a0be2e5e9f7b6fcaf4fbb30ea4e3785ba6baa18ec
